version: 2
jobs:
  build:
    docker:
      - image: novemberde/node-awscli:docker
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t test ./
